resume: #ckpt/model_best.pth
save_dir: ckpt/
log_dir: tensorboard/
gpu: true
n_gpu: 0
metrics:
  - _target_: srcs.model.metric.accuracy
  - _target_: srcs.model.metric.precision
  - _target_: srcs.model.metric.recall
  - _target_: srcs.model.metric.f1

defaults:
  - _self_
  - data: sign_train
  - model: mobilenet
  - hparams: linear_baseline

  - status: train
  - hydra/run/dir: job_timestamp
  - override hydra/job_logging : custom